name: firebase_crashlytics_example
description: Demonstrates how to use the firebase_crashlytics plugin.
author: Flutter Team <flutter-dev@googlegroups.com>

dependencies:
  flutter:
    sdk: flutter
  firebase_crashlytics:
    path: ../
  firebase_core:
    path: ../../../firebase_core/firebase_core

dependency_overrides:
  firebase_crashlytics_platform_interface:
    path: ../../firebase_crashlytics_platform_interface
  firebase_crashlytics:
    path: ../
  firebase_core:
    path: ../../../firebase_core/firebase_core

dev_dependencies:
  pedantic: ^1.8.0
  drive: 0.0.1-6.0.pre
  flutter_driver:
    sdk: flutter
  test: any
  e2e: ^0.6.1

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.8.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"
