name: firebase_crashlytics_legacy
description:
  Flutter plugin for Firebase Crashlytics. It reports uncaught errors to the
  Firebase console. Legacy version with fix for 'Flutter/Flutter.h' file not found #5440
version: 0.4.0+3
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_crashlytics
repository: https://github.com/davejlin/firebase_crashlytics_legacy

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.crashlytics
        pluginClass: FlutterFirebaseCrashlyticsPlugin
      ios:
        pluginClass: FLTFirebaseCrashlyticsPlugin
      macos:
        pluginClass: FLTFirebaseCrashlyticsPlugin

dependencies:
  flutter:
    sdk: flutter
  stack_trace: ^1.9.3
  firebase_core: ^0.7.0
  firebase_core_platform_interface: ^3.0.1
  firebase_crashlytics_platform_interface: ^1.1.6
dev_dependencies:
  pedantic: ^1.8.0
  flutter_test:
    sdk: flutter
  test: ^1.5.1

environment:
  sdk: ">=2.8.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"

